enum IconType {
  NONE = "",

  CARET_DOWN = "\uea67",
  CARET_LEFT = "\uea68",
  CARET_RIGHT = "\uea69",
  CARET_UP = "\uea6a",
  PREV = "\uea9d",
  NEXT = "\ueaa0",
  CERTIFICATE = "\uead4",

  FILE_AUDIO = "\ueb09",
  FILE_DOCUMENT = "\ueb0e",
  FILE_EXE = "\ueb11",
  FILE_IMAGE = "\ueb16",
  FILE_TEXT = "\ueb2a",
  FILE_VIDEO = "\ueb2c",

  UI_ADD = "\uec3e",
  UI_CLOSE = "\uec4f",
  UI_EDIT = "\uec55",
  UI_PLAY = "\uec74",
  UI_ROTATION = "\uec80",
  UI_REMOVE = "\uec7e",
  UI_SETTINGS = "\uec83",
  UI_TAG = "\uec85",

  COPY = "\uedea",
  EDIT_ALT = "\ueded",
  FONT = "\uedef",

  TEXT_HEIGHT = "\uee07",
  BIN = "\ueebb",
  CHECK = "\ueed8",
  CLOCK = "\ueedc",
  CLOSE = "\ueee4",
  CUBE = "\ueef7",
  DASHBOARD = "\ueefa",

  DOWNLOAD = "\uef08",
  DRAG = "\uef0c",
  EDIT = "\uef10",
  EXPAND = "\uef1e",
  EXTERNAL_LINK = "\uef1f",
  FILTER = "\uef29",
  GEAR = "\uef3a",
  GEARS = "\uef3b",
  ID = "\uef4a",
  LINK = "\uef71",
  NOT_ALLOWED = "\uefa9",
  QUESTION = "\uefcc",
  RECYCLE = "\uefd0",
  REFRESH = "\uefd1",
  REPLY = "\uefd4",
  RESIZE = "\uefd5",
  SETTINGS_ALT = "\uefe1",
  SHARE = "\uefe5",

  TAG = "\uf004",
  TAGS = "\uf005",
  UPLOAD = "\uf01c",
}

export default IconType;
